// Code generated by "stringer -trimprefix ErrClass -type ErrorClass"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrClassNone-0]
	_ = x[ErrClassNoMemory-1]
	_ = x[ErrClassOs-2]
	_ = x[ErrClassInvalid-3]
	_ = x[ErrClassReference-4]
	_ = x[ErrClassZlib-5]
	_ = x[ErrClassRepository-6]
	_ = x[ErrClassConfig-7]
	_ = x[ErrClassRegex-8]
	_ = x[ErrClassOdb-9]
	_ = x[ErrClassIndex-10]
	_ = x[ErrClassObject-11]
	_ = x[ErrClassNet-12]
	_ = x[ErrClassTag-13]
	_ = x[ErrClassTree-14]
	_ = x[ErrClassIndexer-15]
	_ = x[ErrClassSSL-16]
	_ = x[ErrClassSubmodule-17]
	_ = x[ErrClassThread-18]
	_ = x[ErrClassStash-19]
	_ = x[ErrClassCheckout-20]
	_ = x[ErrClassFetchHead-21]
	_ = x[ErrClassMerge-22]
	_ = x[ErrClassSsh-23]
	_ = x[ErrClassFilter-24]
	_ = x[ErrClassRevert-25]
	_ = x[ErrClassCallback-26]
	_ = x[ErrClassRebase-29]
	_ = x[ErrClassFilesystem-30]
	_ = x[ErrClassPatch-31]
	_ = x[ErrClassWorktree-32]
	_ = x[ErrClassSHA1-33]
	_ = x[ErrClassHTTP-34]
}

const (
	_ErrorClass_name_0 = "NoneNoMemoryOsInvalidReferenceZlibRepositoryConfigRegexOdbIndexObjectNetTagTreeIndexerSSLSubmoduleThreadStashCheckoutFetchHeadMergeSshFilterRevertCallback"
	_ErrorClass_name_1 = "RebaseFilesystemPatchWorktreeSHA1HTTP"
)

var (
	_ErrorClass_index_0 = [...]uint8{0, 4, 12, 14, 21, 30, 34, 44, 50, 55, 58, 63, 69, 72, 75, 79, 86, 89, 98, 104, 109, 117, 126, 131, 134, 140, 146, 154}
	_ErrorClass_index_1 = [...]uint8{0, 6, 16, 21, 29, 33, 37}
)

func (i ErrorClass) String() string {
	switch {
	case 0 <= i && i <= 26:
		return _ErrorClass_name_0[_ErrorClass_index_0[i]:_ErrorClass_index_0[i+1]]
	case 29 <= i && i <= 34:
		i -= 29
		return _ErrorClass_name_1[_ErrorClass_index_1[i]:_ErrorClass_index_1[i+1]]
	default:
		return "ErrorClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
