// Code generated by "stringer -trimprefix Err -type ErrorCode"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOk-0]
	_ = x[ErrGeneric - -1]
	_ = x[ErrNotFound - -3]
	_ = x[ErrExists - -4]
	_ = x[ErrAmbigious - -5]
	_ = x[ErrBuffs - -6]
	_ = x[ErrUser - -7]
	_ = x[ErrBareRepo - -8]
	_ = x[ErrUnbornBranch - -9]
	_ = x[ErrUnmerged - -10]
	_ = x[ErrNonFastForward - -11]
	_ = x[ErrInvalidSpec - -12]
	_ = x[ErrConflict - -13]
	_ = x[ErrLocked - -14]
	_ = x[ErrModified - -15]
	_ = x[ErrAuth - -16]
	_ = x[ErrCertificate - -17]
	_ = x[ErrApplied - -18]
	_ = x[ErrPeel - -19]
	_ = x[ErrEOF - -20]
	_ = x[ErrUncommitted - -22]
	_ = x[ErrDirectory - -23]
	_ = x[ErrMergeConflict - -24]
	_ = x[ErrPassthrough - -30]
	_ = x[ErrIterOver - -31]
}

const (
	_ErrorCode_name_0 = "IterOverPassthrough"
	_ErrorCode_name_1 = "MergeConflictDirectoryUncommitted"
	_ErrorCode_name_2 = "EOFPeelAppliedCertificateAuthModifiedLockedConflictInvalidSpecNonFastForwardUnmergedUnbornBranchBareRepoUserBuffsAmbigiousExistsNotFound"
	_ErrorCode_name_3 = "GenericOk"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 8, 19}
	_ErrorCode_index_1 = [...]uint8{0, 13, 22, 33}
	_ErrorCode_index_2 = [...]uint8{0, 3, 7, 14, 25, 29, 37, 43, 51, 62, 76, 84, 96, 104, 108, 113, 122, 128, 136}
	_ErrorCode_index_3 = [...]uint8{0, 7, 9}
)

func (i ErrorCode) String() string {
	switch {
	case -31 <= i && i <= -30:
		i -= -31
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case -24 <= i && i <= -22:
		i -= -24
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case -20 <= i && i <= -3:
		i -= -20
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case -1 <= i && i <= 0:
		i -= -1
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
