// Code generated by "stringer -trimprefix Reference -type ReferenceType"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReferenceSymbolic-2]
	_ = x[ReferenceOid-1]
}

const _ReferenceType_name = "OidSymbolic"

var _ReferenceType_index = [...]uint8{0, 3, 11}

func (i ReferenceType) String() string {
	i -= 1
	if i < 0 || i >= ReferenceType(len(_ReferenceType_index)-1) {
		return "ReferenceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ReferenceType_name[_ReferenceType_index[i]:_ReferenceType_index[i+1]]
}
