// Code generated by "stringer -trimprefix RepositoryState -type RepositoryState ."; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RepositoryStateNone-0]
	_ = x[RepositoryStateMerge-1]
	_ = x[RepositoryStateRevert-2]
	_ = x[RepositoryStateRevertSequence-3]
	_ = x[RepositoryStateCherrypick-4]
	_ = x[RepositoryStateCherrypickSequence-5]
	_ = x[RepositoryStateBisect-6]
	_ = x[RepositoryStateRebase-7]
	_ = x[RepositoryStateRebaseInteractive-8]
	_ = x[RepositoryStateRebaseMerge-9]
	_ = x[RepositoryStateApplyMailbox-10]
	_ = x[RepositoryStateApplyMailboxOrRebase-11]
}

const _RepositoryState_name = "NoneMergeRevertRevertSequenceCherrypickCherrypickSequenceBisectRebaseRebaseInteractiveRebaseMergeApplyMailboxApplyMailboxOrRebase"

var _RepositoryState_index = [...]uint8{0, 4, 9, 15, 29, 39, 57, 63, 69, 86, 97, 109, 129}

func (i RepositoryState) String() string {
	if i < 0 || i >= RepositoryState(len(_RepositoryState_index)-1) {
		return "RepositoryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepositoryState_name[_RepositoryState_index[i]:_RepositoryState_index[i+1]]
}
